FROM node:24.11.1-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS deps
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY mobile/package.json ./mobile/
COPY packages/common/package.json ./packages/common/
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM base AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/mobile/node_modules ./mobile/node_modules
COPY --from=deps /app/packages/common/node_modules ./packages/common/node_modules
COPY mobile ./mobile
COPY packages ./packages
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
WORKDIR /app/mobile
EXPOSE 8081
CMD ["pnpm", "web"]
